apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacity-capstone
  template:
    metadata:
      labels:
        app: udacity-capstone
    spec:
      containers:
      - name: udacity-capstone
        image: frenkell/udacity:capstone
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
---
apiVersion: v1
kind: Service
metadata:
  name: dacity-capstone
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: udacity-capstone
  type: LoadBalancer