apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: udacity-capstone-cluster
  region: us-east-1

vpc:
  id: vpc-0d6c2522e54b8b81e
  cidr: "10.100.0.0/16"
  subnets:
    public:
      us-east-1a:
        id: subnet-09d84121ce514226b
      us-east-1b:
        id: subnet-070812ca4802865f2
    private:
      us-east-1a:
        id: subnet-0b68d5676defa8982
      us-east-1b:
        id: subnet-067420dcb34443820

nodeGroups:
  - name: eks-public-workers
    instanceType: t2.medium
    desiredCapacity: 2
  - name: eks-private-workers
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true