apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: udacity-capstone-cluster
  region: us-east-1

vpc:
  id: $VPC
  cidr: "10.100.0.0/16"
  subnets:
    public:
      us-east-1a:
        id: $PUBLIC_SUBNET_1
      us-east-1b:
        id: $PUBLIC_SUBNET_2
    private:
      us-east-1a:
        id: $PRIVATE_SUBNET_1
      us-east-1b:
        id: $PRIVATE_SUBNET_2

nodeGroups:
  - name: eks-public-workers
    instanceType: t2.medium
    desiredCapacity: 2
  - name: eks-private-workers
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true